### ISSUE TITLE
ipn notify url for reference transactions

### ISSUE THREAD

**Issue by tejo** [nov/paypal-express#45]
Hi,

I'm using paypal-express for paypal reference transactions.

All works as aspected but I can't find a way to specify the paypal ipn notify url.

Is it possible?

Thanks

Teo

**Comment by boxmo** [comment]
@tejo can you help me with ipn implementation? How do you figured out? Tks

**Comment by tejo** [comment]
@boxmo I'm really sorry but I no longer work for the company for which I implemented the IPN service so I no longer have access to that code....And honestly I can't remember what how did.
