### ISSUE TITLE
Instant Payment not Redirecting

### ISSUE THREAD

**Issue by Hamdan85** [nov/paypal-express#81]
I dont know if Im wrong, but isnt this gem supposed to redirect you to paypal for processing the payment on the `instant payment`?

I have copied all your code from wiki and happens that it seems to work but do not redirect anything to paypal. 

Thanks in advance

**Comment by joeybeninghove** [comment]
The response that you get back after calling `request.setup` has a `redirect_uri` property on it.  You just need to redirect to that yourself in your own code.
